#include "global.h"
#include "battle.h"
#include "battle_anim.h"
#include "battle_ai_main.h"
#include "battle_ai_util.h"
#include "battle_arena.h"
#include "battle_controllers.h"
#include "battle_interface.h"
#include "battle_main.h"
#include "battle_message.h"
#include "battle_pyramid.h"
#include "battle_scripts.h"
#include "battle_setup.h"
#include "battle_tower.h"
#include "battle_util.h"
#include "berry.h"
#include "bg.h"
#include "data.h"
#include "decompress.h"
#include "dexnav.h"
#include "dma3.h"
#include "event_data.h"
#include "event_scripts.h"
#include "evolution_scene.h"
#include "graphics.h"
#include "gpu_regs.h"
#include "international_string_util.h"
#include "item.h"
#include "link.h"
#include "link_rfu.h"
#include "load_save.h"
#include "main.h"
#include "malloc.h"
#include "m4a.h"
#include "palette.h"
#include "party_menu.h"
#include "pokeball.h"
#include "pokedex.h"
#include "pokemon.h"
#include "random.h"
#include "recorded_battle.h"
#include "roamer.h"
#include "safari_zone.h"
#include "scanline_effect.h"
#include "script.h"
#include "script_pokemon_util.h"
#include "sound.h"
#include "specials.h"
#include "sprite.h"
#include "string_util.h"
#include "strings.h"
#include "task.h"
#include "test_runner.h"
#include "text.h"
#include "trig.h"
#include "tv.h"
#include "util.h"
#include "wild_encounter.h"
#include "window.h"
#include "constants/abilities.h"
#include "constants/battle_move_effects.h"
#include "constants/battle_string_ids.h"
#include "constants/hold_effects.h"
#include "constants/items.h"
#include "constants/moves.h"
#include "constants/party_menu.h"
#include "constants/rgb.h"
#include "constants/songs.h"
#include "constants/trainers.h"
#include "cable_club.h"
#include "tx_randomizer_and_challenges.h"
#include "overworld.h"

const u16 WildBossPetalburgWoods[22][3] = 
{
  {SPECIES_SCIZOR, 55, ITEM_SCIZORITE},
  {SPECIES_PARASECT, 55, ITEM_BUGINIUM_Z},
  {SPECIES_PARASECT, 55, ITEM_BUGINIUM_Z},
  {SPECIES_PINSIR, 55, ITEM_PINSIRITE},
  {SPECIES_HERACROSS, 55, ITEM_HERACRONITE},
  {SPECIES_ARIADOS, 55, ITEM_BUGINIUM_Z},
  {SPECIES_PARASECT, 55,  ITEM_BUGINIUM_Z},
  {SPECIES_PARASECT, 55, ITEM_GRASSIUM_Z},
  {SPECIES_KLEAVOR, 55, ITEM_BUGINIUM_Z},
  {SPECIES_SCOLIPEDE, 55, ITEM_POISONIUM_Z},
  {SPECIES_DRAPION, 55, ITEM_POISONIUM_Z},
// Night
  {SPECIES_TREVENANT, 55, ITEM_GRASSIUM_Z},
  {SPECIES_VILEPLUME, 55, ITEM_GRASSIUM_Z},
  {SPECIES_VICTREEBEL, 55, ITEM_GRASSIUM_Z},
  {SPECIES_MEGANIUM, 55, ITEM_GRASSIUM_Z},
  {SPECIES_SHIFTRY, 55, ITEM_DARKINIUM_Z},
  {SPECIES_TANGROWTH, 55, ITEM_POISONIUM_Z},
  {SPECIES_AMOONGUSS, 55,  ITEM_POISONIUM_Z},
  {SPECIES_SHIINOTIC, 55, ITEM_FAIRIUM_Z},
  {SPECIES_ELDEGOSS, 55, ITEM_GRASSIUM_Z},
  {SPECIES_ARBOK, 55, ITEM_POISONIUM_Z},
  {SPECIES_TOXICROAK, 55, ITEM_POISONIUM_Z},
};

const u16 WildBossFieryPath[22][3] = 
{
  {SPECIES_CHARIZARD, 55, ITEM_CHARIZARDITE_X},
  {SPECIES_ARCANINE_HISUIAN, 55, ITEM_ROCKIUM_Z},
  {SPECIES_CHARIZARD, 55, ITEM_CHARIZARDITE_Y},
  {SPECIES_RAPIDASH, 55, ITEM_FIRIUM_Z},
  {SPECIES_MAGMORTAR, 55, ITEM_FIRIUM_Z},
  {SPECIES_HOUNDOOM, 55, ITEM_HOUNDOOMINITE},
  {SPECIES_CAMERUPT, 55,  ITEM_CAMERUPTITE},
  {SPECIES_CARKOL, 55, ITEM_ROCKIUM_Z},
  {SPECIES_CENTISKORCH, 55, ITEM_FIRIUM_Z},
  {SPECIES_SIMISEAR, 55, ITEM_FIRIUM_Z},
  {SPECIES_RAPIDASH, 55, ITEM_FIRIUM_Z},
  // Night
  {SPECIES_BLAZIKEN, 55, ITEM_BLAZIKENITE},
  {SPECIES_NINETALES, 55, ITEM_FIRIUM_Z},
  {SPECIES_MAROWAK_ALOLAN, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_TYPHLOSION_HISUIAN, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_MAGCARGO, 55, ITEM_FIRIUM_Z},
  {SPECIES_INFERNAPE, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_DARMANITAN, 55,  ITEM_FIRIUM_Z},
  {SPECIES_PYROAR, 55, ITEM_FIRIUM_Z},
  {SPECIES_SALAZZLE, 55, ITEM_POISONIUM_Z},
  {SPECIES_HEATMOR, 55, ITEM_FIRIUM_Z},
  {SPECIES_MAGCARGO, 55, ITEM_FIRIUM_Z},
};

const u16 WildBossNewMauville[22][3] = 
{
  {SPECIES_LUXRAY, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU_ALOLAN, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_ELECTRODE_HISUIAN, 55, ITEM_GRASSIUM_Z},
  {SPECIES_MANECTRIC, 55, ITEM_MANECTITE},
  {SPECIES_MAGNEZONE, 55, ITEM_STEELIUM_Z},
  {SPECIES_TOXTRICITY, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_VIKAVOLT, 55,  ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU_ALOLAN, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU_ALOLAN, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU_ALOLAN, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_RAICHU_ALOLAN, 55, ITEM_PSYCHIUM_Z},
  // Night
  {SPECIES_ELECTIVIRE, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_BOLTUND, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_TOXTRICITY_LOW_KEY, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_ZEBSTRIKA, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_GOLEM_ALOLAN, 55, ITEM_ROCKIUM_Z},
  {SPECIES_ELECTRODE, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_GALVANTULA, 55,  ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_RAICHU, 55, ITEM_ELECTRIUM_Z},
};

const u16 WildBossRoute111[22][3] = 
{
  {SPECIES_TYRANITAR, 55, ITEM_TYRANITARITE},
  {SPECIES_DONPHAN, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_NIDOKING, 55, ITEM_NORMALIUM_Z},
  {SPECIES_STEELIX, 55, ITEM_STEELIXITE},
  {SPECIES_HIPPOWDON, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_MUDSDALE, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_URSALUNA, 55,  ITEM_GROUNDIUM_Z},
  {SPECIES_CACTURNE, 55, ITEM_GRASSIUM_Z},
  {SPECIES_DUGTRIO, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_DUGTRIO, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_DUGTRIO, 55, ITEM_GROUNDIUM_Z},
  // Night
  {SPECIES_KROOKODILE, 55, ITEM_DARKINIUM_Z},
  {SPECIES_SANDACONDA, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_NIDOQUEEN, 55, ITEM_NORMALIUM_Z},
  {SPECIES_EXCADRILL, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_RHYPERIOR, 55, ITEM_ROCKIUM_Z},
  {SPECIES_DUGTRIO_ALOLAN, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_GOLEM, 55, ITEM_ROCKIUM_Z},
  {SPECIES_MARACTUS, 55, ITEM_GRASSIUM_Z},
  {SPECIES_DUGTRIO_ALOLAN, 55, ITEM_STEELIUM_Z},
  {SPECIES_DUGTRIO_ALOLAN, 55, ITEM_GROUNDIUM_Z},
  {SPECIES_DUGTRIO_ALOLAN, 55, ITEM_STEELIUM_Z},
};

const u16 WildBossRoute118[22][3] = 
{
  {SPECIES_PIDGEOT, 55, ITEM_PIDGEOTITE},
  {SPECIES_DRAGONITE, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_YANMEGA, 55, ITEM_BUGINIUM_Z},
  {SPECIES_VESPIQUEN, 55, ITEM_BUGINIUM_Z},
  {SPECIES_FLYGON, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_BEEDRILL, 55, ITEM_BEEDRILLITE},
  {SPECIES_PELIPPER, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_SWELLOW, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_SWELLOW, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_SWELLOW, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_SWELLOW, 55,  ITEM_FLYINIUM_Z},
  // Night
  {SPECIES_MANDIBUZZ, 55, ITEM_DARKINIUM_Z},
  {SPECIES_NOIVERN, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_CROBAT, 55, ITEM_POISONIUM_Z},
  {SPECIES_NOCTOWL, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_TOGEKISS, 55, ITEM_FAIRIUM_Z},
  {SPECIES_SWANNA, 55, ITEM_WATERIUM_Z},
  {SPECIES_SWOOBAT, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_SWOOBAT, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_SWOOBAT, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_SWOOBAT, 55, ITEM_FLYINIUM_Z},
  {SPECIES_SWOOBAT, 55, ITEM_FLYINIUM_Z},
};

const u16 WildBossRoute103[22][3] =
{
  {SPECIES_PANGORO, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_GOGOAT, 55, ITEM_GRASSIUM_Z},
  {SPECIES_APPLETUN, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_ROSERADE, 55, ITEM_GRASSIUM_Z},
  {SPECIES_MIENSHAO, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_GRAPPLOCT, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_POLITOED, 55,  ITEM_WATERIUM_Z},
  {SPECIES_SLOWBRO, 55,  ITEM_SLOWBRONITE},
  {SPECIES_SAWK, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_GOGOAT, 55, ITEM_GRASSIUM_Z},
  {SPECIES_GOGOAT, 55, ITEM_GRASSIUM_Z},
  // Night
  {SPECIES_SWAMPERT, 55, ITEM_SWAMPERTITE},
  {SPECIES_POLIWRATH, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_HYPNO, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_KANGASKHAN, 55, ITEM_KANGASKHANITE},
  {SPECIES_EXPLOUD, 55, ITEM_NORMALIUM_Z},
  {SPECIES_SEISMITOAD, 55, ITEM_WATERIUM_Z},
  {SPECIES_THROH, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_POLIWRATH, 55, ITEM_WATERIUM_Z},
  {SPECIES_POLIWRATH, 55, ITEM_WATERIUM_Z},
  {SPECIES_POLIWRATH, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_POLIWRATH, 55, ITEM_FIGHTINIUM_Z},
};

const u16 WildBossMtPyre[22][3] =
{
  {SPECIES_GENGAR, 55, ITEM_GENGARITE},
  {SPECIES_ZOROARK_HISUIAN, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_COFAGRIGUS, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_MISMAGIUS, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_CHANDELURE, 55, ITEM_FIRIUM_Z},
  {SPECIES_CURSOLA, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_ZOROARK_HISUIAN, 55,  ITEM_NORMALIUM_Z},
  {SPECIES_ZOROARK_HISUIAN, 55,  ITEM_GHOSTIUM_Z},
  {SPECIES_ZOROARK_HISUIAN, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_ZOROARK_HISUIAN, 55, ITEM_NORMALIUM_Z},
  {SPECIES_ZOROARK_HISUIAN, 55, ITEM_NORMALIUM_Z},
  // Night
  {SPECIES_GOLURK, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_DRIFBLIM, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_MAROWAK_ALOLAN, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_SPIRITOMB, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_ZOROARK, 55, ITEM_DARKINIUM_Z},
  {SPECIES_RUNERIGUS, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_ZOROARK, 55, ITEM_DARKINIUM_Z},
  {SPECIES_ZOROARK, 55, ITEM_DARKINIUM_Z},
  {SPECIES_ZOROARK, 55, ITEM_DARKINIUM_Z},
  {SPECIES_ZOROARK, 55, ITEM_DARKINIUM_Z},
  {SPECIES_ZOROARK, 55, ITEM_DARKINIUM_Z},
};

const u16 WildBossRoute119[22][3] =
{
  {SPECIES_TORTERRA, 55, ITEM_GRASSIUM_Z},
  {SPECIES_EXEGGUTOR_ALOLAN, 55, ITEM_GRASSIUM_Z},
  {SPECIES_SUNFLORA, 55, ITEM_GRASSIUM_Z},
  {SPECIES_LUDICOLO, 55, ITEM_GRASSIUM_Z},
  {SPECIES_TROPIUS, 55, ITEM_GRASSIUM_Z},
  {SPECIES_CARNIVINE, 55, ITEM_GRASSIUM_Z},
  {SPECIES_DECIDUEYE, 55,  ITEM_GRASSIUM_Z},
  {SPECIES_EXEGGUTOR_ALOLAN, 55,  ITEM_GRASSIUM_Z},
  {SPECIES_EXEGGUTOR_ALOLAN, 55, ITEM_GRASSIUM_Z},
  {SPECIES_EXEGGUTOR_ALOLAN, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_EXEGGUTOR_ALOLAN, 55, ITEM_DRAGONIUM_Z},
  // Night
  {SPECIES_DECIDUEYE_HISUIAN, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_EXEGGCUTE, 55, ITEM_GRASSIUM_Z},
  {SPECIES_VENUSAUR, 55, ITEM_VENUSAURITE},
  {SPECIES_SCEPTILE, 55, ITEM_SCEPTILITE},
  {SPECIES_SAWSBUCK_SUMMER, 55, ITEM_GRASSIUM_Z},
  {SPECIES_APPLETUN, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_EXEGGCUTE, 55, ITEM_GRASSIUM_Z},
  {SPECIES_EXEGGCUTE, 55, ITEM_GRASSIUM_Z},
  {SPECIES_EXEGGCUTE, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_EXEGGCUTE, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_EXEGGCUTE, 55, ITEM_PSYCHIUM_Z},
};

const u16 WildBossRoute127UW[22][3] =
{
  {SPECIES_HUNTAIL, 55, ITEM_WATERIUM_Z},
  {SPECIES_LANTURN, 55, ITEM_WATERIUM_Z},
  {SPECIES_MANTINE, 55, ITEM_WATERIUM_Z},
  {SPECIES_SHARPEDO, 55, ITEM_SHARPEDONITE},
  {SPECIES_BASCULEGION, 55, ITEM_WATERIUM_Z},
  {SPECIES_WISHIWASHI_SCHOOL, 55, ITEM_WATERIUM_Z},
  {SPECIES_RELICANTH, 55,  ITEM_WATERIUM_Z},
  {SPECIES_LANTURN, 55,  ITEM_WATERIUM_Z},
  {SPECIES_LANTURN, 55, ITEM_WATERIUM_Z},
  {SPECIES_LANTURN, 55, ITEM_ELECTRIUM_Z},
  {SPECIES_LANTURN, 55, ITEM_ELECTRIUM_Z},
  // Night
  {SPECIES_GOREBYSS, 55, ITEM_WATERIUM_Z},
  {SPECIES_GYARADOS, 55, ITEM_GYARADOSITE},
  {SPECIES_TENTACRUEL, 55, ITEM_WATERIUM_Z},
  {SPECIES_BASCULEGION_FEMALE, 55, ITEM_WATERIUM_Z},
  {SPECIES_CLAWITZER, 55, ITEM_WATERIUM_Z},
  {SPECIES_PRIMARINA, 55, ITEM_WATERIUM_Z},
  {SPECIES_BARRASKEWDA, 55, ITEM_WATERIUM_Z},
  {SPECIES_KINGDRA, 55, ITEM_WATERIUM_Z},
  {SPECIES_TENTACRUEL, 55, ITEM_WATERIUM_Z},
  {SPECIES_TENTACRUEL, 55, ITEM_POISONIUM_Z},
  {SPECIES_TENTACRUEL, 55, ITEM_POISONIUM_Z},
};

const u16 WildBossRoute109[22][3] =
{
  {SPECIES_FLOATZEL, 55, ITEM_WATERIUM_Z},
  {SPECIES_GOLDUCK, 55, ITEM_WATERIUM_Z},
  {SPECIES_SLOWBRO, 55, ITEM_SLOWBRONITE},
  {SPECIES_CRAWDAUNT, 55, ITEM_WATERIUM_Z},
  {SPECIES_GASTRODON, 55, ITEM_WATERIUM_Z},
  {SPECIES_WALREIN, 55, ITEM_WATERIUM_Z},
  {SPECIES_QUAGSIRE, 55,  ITEM_WATERIUM_Z},
  {SPECIES_JELLICENT, 55,  ITEM_WATERIUM_Z},
  {SPECIES_JELLICENT, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_JELLICENT, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_JELLICENT, 55, ITEM_GHOSTIUM_Z},
  // Night
  {SPECIES_BLASTOISE, 55, ITEM_BLASTOISINITE},
  {SPECIES_BIBAREL, 55, ITEM_WATERIUM_Z},
  {SPECIES_GASTRODON_EAST_SEA, 55, ITEM_WATERIUM_Z},
  {SPECIES_SEISMITOAD, 55, ITEM_WATERIUM_Z},
  {SPECIES_CARRACOSTA, 55, ITEM_WATERIUM_Z},
  {SPECIES_EMPOLEON, 55, ITEM_WATERIUM_Z},
  {SPECIES_KINGLER, 55, ITEM_WATERIUM_Z},
  {SPECIES_JELLICENT, 55, ITEM_WATERIUM_Z},
  {SPECIES_JELLICENT, 55, ITEM_WATERIUM_Z},
  {SPECIES_JELLICENT, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_JELLICENT, 55, ITEM_GHOSTIUM_Z},
};

const u16 WildBossIceRoom[22][3] =
{
  {SPECIES_FROSLASS, 55, ITEM_ICIUM_Z},
  {SPECIES_ABOMASNOW, 55, ITEM_ABOMASITE},
  {SPECIES_BEARTIC, 55, ITEM_ICIUM_Z},
  {SPECIES_MR_RIME, 55, ITEM_ICIUM_Z},
  {SPECIES_DARMANITAN_GALARIAN, 55, ITEM_ICIUM_Z},
  {SPECIES_VULPIX_ALOLAN, 55, ITEM_ICIUM_Z},
  {SPECIES_VANILLUXE, 55,  ITEM_ICIUM_Z},
  {SPECIES_AVALUGG_HISUIAN, 55,  ITEM_ICIUM_Z},
  {SPECIES_AVALUGG_HISUIAN, 55, ITEM_ICIUM_Z},
  {SPECIES_AVALUGG_HISUIAN, 55, ITEM_ROCKIUM_Z},
  {SPECIES_AVALUGG_HISUIAN, 55, ITEM_ROCKIUM_Z},
  // Night
  {SPECIES_GLALIE, 55, ITEM_GLALITITE},
  {SPECIES_WEAVILE, 55, ITEM_ICIUM_Z},
  {SPECIES_MAMOSWINE, 55, ITEM_ICIUM_Z},
  {SPECIES_CRYOGONAL, 55, ITEM_ICIUM_Z},
  {SPECIES_AURORUS, 55, ITEM_ICIUM_Z},
  {SPECIES_CRABOMINABLE, 55, ITEM_ICIUM_Z},
  {SPECIES_SANDSLASH_ALOLAN, 55, ITEM_ICIUM_Z},
  {SPECIES_AVALUGG, 55, ITEM_ICIUM_Z},
  {SPECIES_AVALUGG, 55, ITEM_ICIUM_Z},
  {SPECIES_AVALUGG, 55, ITEM_ICIUM_Z},
  {SPECIES_AVALUGG, 55, ITEM_ICIUM_Z},
};

const u16 WildBossChamber[22][3] =
{
  {SPECIES_METAGROSS, 55, ITEM_METAGROSSITE},
  {SPECIES_GOODRA_HISUIAN, 55, ITEM_STEELIUM_Z},
  {SPECIES_MELMETAL, 55, ITEM_STEELIUM_Z},
  {SPECIES_PERRSERKER, 55, ITEM_STEELIUM_Z},
  {SPECIES_COPPERAJAH, 55, ITEM_STEELIUM_Z},
  {SPECIES_KLINKLANG, 55, ITEM_STEELIUM_Z},
  {SPECIES_AGGRON, 55,  ITEM_AGGRONITE},
  {SPECIES_AEGISLASH, 55,  ITEM_STEELIUM_Z},
  {SPECIES_AEGISLASH, 55, ITEM_STEELIUM_Z},
  {SPECIES_AEGISLASH, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_AEGISLASH, 55, ITEM_GHOSTIUM_Z},
  // Night
  {SPECIES_LUCARIO, 55, ITEM_LUCARIONITE},
  {SPECIES_FERROTHORN, 55, ITEM_STEELIUM_Z},
  {SPECIES_STEELIX, 55, ITEM_STEELIXITE},
  {SPECIES_DURALUDON, 55, ITEM_STEELIUM_Z},
  {SPECIES_BRONZONG, 55, ITEM_STEELIUM_Z},
  {SPECIES_BASTIODON, 55, ITEM_STEELIUM_Z},
  {SPECIES_ZYGARDE_COMPLETE, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_AEGISLASH_BLADE, 55, ITEM_STEELIUM_Z},
  {SPECIES_AEGISLASH_BLADE, 55, ITEM_STEELIUM_Z},
  {SPECIES_AEGISLASH_BLADE, 55, ITEM_GHOSTIUM_Z},
  {SPECIES_AEGISLASH_BLADE, 55, ITEM_GHOSTIUM_Z},
};

const u16 WildBossF2[22][3] =
{
  {SPECIES_AMPHAROS, 55, ITEM_AMPHAROSITE},
  {SPECIES_MIGHTYENA, 55, ITEM_DARKINIUM_Z},
  {SPECIES_SHIFTRY, 55, ITEM_DARKINIUM_Z},
  {SPECIES_WEAVILE, 55, ITEM_DARKINIUM_Z},
  {SPECIES_ABSOL, 55, ITEM_ABSOLITE},
  {SPECIES_MUK, 55, ITEM_POISONIUM_Z},
  {SPECIES_SCRAFTY, 55,  ITEM_FIGHTINIUM_Z},
  {SPECIES_AMBIPOM, 55,  ITEM_NORMALIUM_Z},
  {SPECIES_GRIMMSNARL, 55, ITEM_FAIRIUM_Z},
  {SPECIES_MUK_ALOLAN, 55, ITEM_POISONIUM_Z},
  {SPECIES_SAMUROTT_HISUIAN, 55, ITEM_WATERIUM_Z},
  // Night
  {SPECIES_TAUROS, 55, ITEM_NORMALIUM_Z},
  {SPECIES_SNORLAX, 55, ITEM_SNORLIUM_Z},
  {SPECIES_URSALUNA, 55, ITEM_NORMALIUM_Z},
  {SPECIES_BLISSEY, 55, ITEM_NORMALIUM_Z},
  {SPECIES_SLAKING, 55, ITEM_NORMALIUM_Z},
  {SPECIES_EXPLOUD, 55, ITEM_NORMALIUM_Z},
  {SPECIES_LOPUNNY, 55, ITEM_LOPUNNITE},
  {SPECIES_AUDINO, 55, ITEM_AUDINITE},
  {SPECIES_DRAMPA, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_WYRDEER, 55, ITEM_NORMALIUM_Z},
  {SPECIES_BEWEAR, 55, ITEM_FIGHTINIUM_Z},
};

const u16 WildBossGraniteCave[22][3] =
{
  {SPECIES_SABLEYE, 55, ITEM_SABLENITE},
  {SPECIES_EXPLOUD, 55, ITEM_NORMALIUM_Z},
  {SPECIES_AUDINO, 55, ITEM_AUDINITE},
  {SPECIES_TAUROS, 55, ITEM_NORMALIUM_Z},
  {SPECIES_SNORLAX, 55, ITEM_SNORLIUM_Z},
  {SPECIES_DRAMPA, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_MUK_ALOLAN, 55, ITEM_POISONIUM_Z},
  {SPECIES_MIGHTYENA, 55, ITEM_DARKINIUM_Z},
  {SPECIES_ABSOL, 55, ITEM_ABSOLITE},
  {SPECIES_OBSTAGOON, 55, ITEM_DARKINIUM_Z},
  {SPECIES_BLISSEY, 55, ITEM_NORMALIUM_Z},
  // Night
  {SPECIES_WEAVILE, 55, ITEM_DARKINIUM_Z},
  {SPECIES_SAMUROTT_HISUIAN, 55, ITEM_WATERIUM_Z},
  {SPECIES_LOPUNNY, 55, ITEM_LOPUNNITE},
  {SPECIES_SCRAFTY, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_MUK, 55, ITEM_POISONIUM_Z},
  {SPECIES_URSALUNA, 55, ITEM_NORMALIUM_Z},
  {SPECIES_BEWEAR, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_WYRDEER, 55, ITEM_NORMALIUM_Z},
  {SPECIES_SHIFTRY, 55, ITEM_DARKINIUM_Z},
  {SPECIES_SLAKING, 55, ITEM_NORMALIUM_Z},
  {SPECIES_GRIMMSNARL, 55, ITEM_FAIRIUM_Z},
};

const u16 WildBossOrigin[22][3] =
{
  {SPECIES_OBSTAGOON, 55, ITEM_DARKINIUM_Z},
  {SPECIES_MEDICHAM, 55, ITEM_MEDICHAMITE},
  {SPECIES_MIGHTYENA, 55, ITEM_DARKINIUM_Z},
  {SPECIES_ABSOL, 55, ITEM_ABSOLITE},
  {SPECIES_AUDINO, 55, ITEM_AUDINITE},
  {SPECIES_GRIMMSNARL, 55, ITEM_FAIRIUM_Z},
  {SPECIES_SHIFTRY, 55, ITEM_DARKINIUM_Z},
  {SPECIES_SNORLAX, 55, ITEM_NORMALIUM_Z},
  {SPECIES_BEWEAR, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_BLISSEY, 55, ITEM_NORMALIUM_Z},
  {SPECIES_MUK, 55, ITEM_POISONIUM_Z},
  // Night
  {SPECIES_MUK_ALOLAN, 55, ITEM_POISONIUM_Z},
  {SPECIES_TAUROS, 55, ITEM_NORMALIUM_Z},
  {SPECIES_WEAVILE, 55, ITEM_DARKINIUM_Z},
  {SPECIES_EXPLOUD, 55, ITEM_NORMALIUM_Z},
  {SPECIES_LOPUNNY, 55, ITEM_LOPUNNITE},
  {SPECIES_SCRAFTY, 55, ITEM_FIGHTINIUM_Z},
  {SPECIES_URSALUNA, 55, ITEM_NORMALIUM_Z},
  {SPECIES_WYRDEER, 55, ITEM_NORMALIUM_Z},
  {SPECIES_DRAMPA, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_SLAKING, 55, ITEM_NORMALIUM_Z},
  {SPECIES_SAMUROTT_HISUIAN, 55, ITEM_WATERIUM_Z},
};

const u16 WildBossRoute127[22][3] = 
{
  {SPECIES_STARAPTOR, 55, ITEM_FLYINIUM_Z},
  {SPECIES_ALTARIA, 55, ITEM_ALTARIANITE},
  {SPECIES_BRAVIARY, 55, ITEM_FLYINIUM_Z},
  {SPECIES_TALONFLAME, 55, ITEM_FIRIUM_Z},
  {SPECIES_CRAMORANT, 55, ITEM_WATERIUM_Z},
  {SPECIES_SWANNA, 55, ITEM_WATERIUM_Z},
  {SPECIES_UNFEZANT, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55,  ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55,  ITEM_FLYINIUM_Z},
  // Night
  {SPECIES_BRAVIARY_HISUIAN, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_NOIVERN, 55, ITEM_DRAGONIUM_Z},
  {SPECIES_CROBAT, 55, ITEM_POISONIUM_Z},
  {SPECIES_NOCTOWL, 55, ITEM_PSYCHIUM_Z},
  {SPECIES_TOGEKISS, 55, ITEM_FAIRIUM_Z},
  {SPECIES_BEAUTIFLY, 55, ITEM_BUGINIUM_Z},
  {SPECIES_UNFEZANT, 55, ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55, ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55, ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55, ITEM_FLYINIUM_Z},
  {SPECIES_UNFEZANT, 55, ITEM_FLYINIUM_Z},
};

static u8 gSavedIndex;
static u8 gSavedTime;

void GenerateWildBoss(void) 
{
  u8 mapid = GetCurrentRegionMapSectionId();
  u8 randomIndex = 0;
  const u16* wildBossArray = NULL;

  if (gSavedTime != gTimeOfDay) {
    FlagClear(FLAG_UNUSED_0x95E);
  }

  if (FlagGet(FLAG_UNUSED_0x95E)) {
    randomIndex = gSavedIndex;
  } else {
    randomIndex = (gTimeOfDay != TIME_OF_DAY_NIGHT) ? Random() % 10 : 11 + (Random() % (22 - 11));
    gSavedIndex = randomIndex;
    gSavedTime = gTimeOfDay;
    FlagSet(FLAG_UNUSED_0x95E);
  }

  switch (mapid) {
    case MAPSEC_PETALBURG_WOODS:
      wildBossArray = WildBossPetalburgWoods[randomIndex];
      break;
    case MAPSEC_FIERY_PATH:
      wildBossArray = WildBossFieryPath[randomIndex];
      break;
    case MAPSEC_NEW_MAUVILLE:
      wildBossArray = WildBossNewMauville[randomIndex];
      break;
    case MAPSEC_ROUTE_111:
      wildBossArray = WildBossRoute111[randomIndex];
      break;
    case MAPSEC_ROUTE_118:
      wildBossArray = WildBossRoute118[randomIndex];
      break;
    case MAPSEC_ROUTE_103:
      wildBossArray = WildBossRoute103[randomIndex];
      break;
    case MAPSEC_MT_PYRE:
      wildBossArray = WildBossMtPyre[randomIndex];
      break;
    case MAPSEC_ROUTE_119:
      wildBossArray = WildBossRoute119[randomIndex];
      break;
    case MAPSEC_UNDERWATER_127:
      wildBossArray = WildBossRoute127UW[randomIndex];
      break;
    case MAPSEC_ROUTE_109:
      wildBossArray = WildBossRoute109[randomIndex];
      break;
    case MAPSEC_SHOAL_CAVE:
      wildBossArray = WildBossIceRoom[randomIndex];
      break;
    case MAPSEC_SEALED_CHAMBER:
      wildBossArray = WildBossChamber[randomIndex];
      break;
    case MAPSEC_FALLARBOR_TOWN:
      wildBossArray = WildBossF2[randomIndex];
      break;
    case MAPSEC_GRANITE_CAVE:
      wildBossArray = WildBossGraniteCave[randomIndex];
      break;
    case MAPSEC_CAVE_OF_ORIGIN:
      wildBossArray = WildBossOrigin[randomIndex];
      break;
    case MAPSEC_ROUTE_127:
      wildBossArray = WildBossRoute127[randomIndex];
      break;
    default:
      break;
  }

  if (wildBossArray != NULL) {
    VarSet(VAR_TEMP_6, wildBossArray[0]);
    VarSet(VAR_TEMP_7, wildBossArray[1]);
    VarSet(VAR_TEMP_8, wildBossArray[2]);
  }
}
