#ifndef GUARD_CONSTANTS_VERSIONING_H
#define GUARD_CONSTANTS_VERSIONING_H

#define SAVE_VERSION_0 0
#define SAVE_VERSION_1 1
#define SAVE_VERSION_2 2
#define SAVE_VERSION_3 3
#define SAVE_VERSION_4 4
#define SAVE_VERSION_5 5
#define SAVE_VERSION_6 6

#define SAVE_VERSION (SAVE_VERSION_6)

#endif // GUARD_CONSTANTS_VERSIONING_H
